name: Chronicle

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-chronicle:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Chronicle script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          LAST_RUN_TIMESTAMP: ${{ env.LAST_RUN_TIMESTAMP }}
        run: |
          python main.py

      - name: Update Last Run Timestamp (PAT optional)
        if: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "LAST_RUN_TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          gh secret set LAST_RUN_TIMESTAMP --body "$LAST_RUN_TIMESTAMP"